### ISSUE TITLE
Page Not Found error happens when we click links at user manual page

### ISSUE THREAD

**Issue by xfeep** [atomix/atomix.github.io#19]
The links at page https://atomix.io/docs/latest/user-manual/ are broken.

**Comment by kuujo** [comment]
I think it’s the mobile links that are broken. Browsers seem to work fine.

**Comment by kuujo** [comment]
Should be fixed. Can you test and reopen if you're still seeing the issue?

**Comment by xfeep** [comment]
Browsers still can not work.

1. Go to https://atomix.io/docs/latest/user-manual/
2. Click `Cluster` in the left navigator panel
3. Browser will go to https://atomix.io/docs/latest/user-manual/cluster and get Page not found error.

**Comment by xfeep** [comment]
BTW I have no permission to reopen it.
